/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-in-the-cloud-b270497defe24f9cb497b9a075eeb28f
Title: FREE - SkyBox In The Cloud
*/

import { useGLTF } from '@react-three/drei';

import skyScene from '../assets/3d/sky.glb';
import { useRef } from 'react';
import { useFrame } from '@react-three/fiber';

const Sky = ({ isRotating }) => {
	const sky = useGLTF(skyScene);
	const skyRef = useRef();

	/**
	 * Note: Animation names can be found on the Sketchfab website where the 3D model is hosted.
	 * It ensures smooth animations by making the rotation from rate-independent.
	 * 'delta' represents the time in seconds since the last frame
	 */
	useFrame((_, delta) => {
		if (isRotating) {
			skyRef.current.rotation.y += 0.25 * delta;
		}
	});

	return (
		<mesh ref={skyRef}>
			<primitive object={sky.scene} />
		</mesh>
	);
};

export default Sky;
