/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-in-the-cloud-b270497defe24f9cb497b9a075eeb28f
Title: FREE - SkyBox In The Cloud
*/

import { useGLTF } from '@react-three/drei';

import skyScene from '../assets/3d/sky.glb';

const Sky = (props) => {
	const sky = useGLTF(skyScene);
	return (
		<mesh>
			<primitive object={sky.scene} />
		</mesh>
	);
};

export default Sky;
